#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#compositor
picom -f &

#wallpaper
nitrogen --restore &

#keyboard layout
setxkbmap -layout us -variant intl &

#cursor
xsetroot -cursor_name left_ptr &

#polybar
$HOME/.config/polybar/launch.sh

#mpd meme
mpd .config/mpd/mpd.conf &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           2
#bspc config focused_border_color "#7aa2f7"
bspc config focused_border_color  "#444b6a"
bspc config active_border_color  "#32344a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop='^5' state=floating #follow=on
bspc rule -a mpv desktop='^6' state=floating #follow=on
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Gnome-control-center state=floating
bspc rule -a KeePassXC state=floating
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
